version: "3"
services:
  hk-mysql: #서비스명
    restart: always
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ahn
      MYSQL_ROOT_PASSWORD: P!ssw0rd
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ../db:/var/lib/mysql
      #- db:/var/lib/mysql # insert, update 데이터 컨테이너 내려가면 다 날라감.
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  backend:
    restart: always
    build: ./book-backend/.
    ports:
      - "4000:4000"
    depends_on:
      - hk-mysql

  frontend:
    restart: always
    build: ./book-frontend/.
    ports:
      - "80:80"
    depends_on:
      - backend
